# Site settings
title: Barbados
client:
  name: Karibischer Sehnsuchtsort
  link: "http://bit.ly/2BYpVBV"
core-se-link: https://www.secretescapes.de/aktuelle-angebote?utm_source=SE&utm_medium=hub&utm_campaign=barbados_DE_2019
description: >
  An was denken Sie beim Namen Barbados? Karibisches Meer, Sonne, Rhythmen und Rum fallen einem sofort ein. Doch die Insel hat noch vieles mehr zu bieten und ist mit über 92 km unberührter, idyllischer Küste ein erstklassiges Traumziel.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/de/barbados" # the subpath of your site, e.g. /blog/
img:     "/de/barbados/_assets/img"
css:     "/de/barbados/_assets/css"
js:      "/de/barbados/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed
