# Site settings
title: Barbados
client:
  name: Barbados
  link: "https://www.visitbarbados.org/fr/"

core-se-link: https://www.evasionssecretes.fr/vente-promotion?utm_source=SE&utm_medium=hub&utm_campaign=barbados_FR
description: >
  Se ti diciamo Barbados, a cosa pensi? Mare cristallino, sole tutto l'anno, ritmi caraibici e rum - certo, ma quest'isola con i suoi 92 km di costa incontaminata ha molto di più da offrire. Visita Barbados e lasciati conquistare dalla travolgente ospitalità dei Bajan, nuota con le tartarughe marine, avventurati a piedi o in bici nella natura mozzafiato, passando dai litorali scenografici all'entroterra selvaggio. Lo stile di vita di quest'isola, le sue spiagge paradisiache e l'universo di esperienze da provare portano Barbados direttamente in cima alla tua lista di viaggi da fare.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/2019/barbados-fr" # the subpath of your site, e.g. /blog/
img:     "/2019/barbados-fr/_assets/img"
css:     "/2019/barbados-fr/_assets/css"
js:      "/2019/barbados-fr/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed
